using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;

namespace SaccoBook.Modules.Settings.DocumentApprovals
{
    public partial class DocumentApprovers : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public DocumentApprovers()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btn_approvaldocument_ItemClick(object sender, ItemClickEventArgs e)
        {
            ApprovalDocument _ApprovalDocument = new ApprovalDocument();
            _ApprovalDocument.ShowDialog();
        }

        private void btn_approvaluser_ItemClick(object sender, ItemClickEventArgs e)
        {
            DocumentApprovalUser _DocumentApprovers = new DocumentApprovalUser();
            _DocumentApprovers.ShowDialog();
        }
    }
}