//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvalentry
    {
        public int EntryNumber { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public int SequenceNumber { get; set; }
        public string SenderId { get; set; }
        public string ApproverId { get; set; }
        public string Status { get; set; }
        public string DateTimeSentForApproval { get; set; }
        public string LastModifiedAt { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
