//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class approvaluser
    {
        public int Id { get; set; }
        public string DocumentType { get; set; }
        public string Approver { get; set; }
        public int ApprovalSequence { get; set; }
        public string ApproverEmail { get; set; }
        public string SubstituteApprover { get; set; }
        public string SubstituteApproverEmail { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
