//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalledgeraccount
    {
        public string Code { get; set; }
        public string ParentCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AccountType { get; set; }
        public string IncomeBalanceSheet { get; set; }
        public short DirectPosting { get; set; }
        public double BudgetedAmount { get; set; }
        public double BalanceAtDate { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public short IsBlocked { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
