//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanprocucttype
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int InterestRate { get; set; }
        public byte RequiresMakerChecker { get; set; }
        public string InterestCalculationType { get; set; }
        public double MaximumLoanAmount { get; set; }
        public int MaxRepaymentPeriodInMonths { get; set; }
        public double MinimumDepositContribution { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
