//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberloanrepayment
    {
        public string DocumentNumber { get; set; }
        public string LoanId { get; set; }
        public System.DateTime Date { get; set; }
        public string PaidBy { get; set; }
        public string Source { get; set; }
        public string SourceAccountNumber { get; set; }
        public string PayingAccountNumber { get; set; }
        public string BankReference { get; set; }
        public string Narration { get; set; }
        public double InstallmentAmount { get; set; }
        public double InterestAmount { get; set; }
        public double Balance { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    
        public virtual memberloan memberloan { get; set; }
    }
}
