//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class membersaving
    {
        public string DocumentNumber { get; set; }
        public string MembershipNumber { get; set; }
        public string TransactionType { get; set; }
        public string Source { get; set; }
        public string SourceAccount { get; set; }
        public string AccountType { get; set; }
        public string Destination { get; set; }
        public string DestinationAccount { get; set; }
        public string Description { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string GLAccount { get; set; }
        public double CreditAmount { get; set; }
        public double DebitAmount { get; set; }
        public Nullable<double> TransactionAmount { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    
        public virtual member member { get; set; }
    }
}
