//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class membersavingsaccount
    {
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string AccountName { get; set; }
        public string MembershipNumber { get; set; }
        public double CreditAmount { get; set; }
        public double DebitAmount { get; set; }
        public double Balance { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    
        public virtual member member { get; set; }
        public virtual membersavingsaccount membersavingsaccounts1 { get; set; }
        public virtual membersavingsaccount membersavingsaccount1 { get; set; }
    }
}
