//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class membersharecapital
    {
        public int Id { get; set; }
        public string DocumentId { get; set; }
        public string MemberNumber { get; set; }
        public System.DateTime Date { get; set; }
        public long Amount { get; set; }
    }
}
