//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.memberbankaccounts = new HashSet<memberbankaccount>();
            this.memberbeneficiaries = new HashSet<memberbeneficiary>();
            this.memberkins = new HashSet<memberkin>();
            this.memberloans = new HashSet<memberloan>();
            this.membermonthlycontributions = new HashSet<membermonthlycontribution>();
            this.membersavings = new HashSet<membersaving>();
            this.membersavingsaccounts = new HashSet<membersavingsaccount>();
            this.Signatories = new HashSet<Signatory>();
        }
    
        public string MembershipNumber { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string AlternativeNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string NationalIdNumber { get; set; }
        public string TaxPIN { get; set; }
        public string Address { get; set; }
        public byte[] Photo { get; set; }
        public string Password { get; set; }
        public string SourceOfIncome { get; set; }
        public string Employer { get; set; }
        public string JobPosition { get; set; }
        public string PayrollNumber { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerTelephoneNumber { get; set; }
        public double GrossMonthlyIncome { get; set; }
        public System.DateTime DateJoined { get; set; }
        public string MembershipStatus { get; set; }
        public string MembershipType { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memberbankaccount> memberbankaccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memberbeneficiary> memberbeneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memberkin> memberkins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memberloan> memberloans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membermonthlycontribution> membermonthlycontributions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membersaving> membersavings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membersavingsaccount> membersavingsaccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signatory> Signatories { get; set; }
    }
}
