//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class membermonthlycontribution
    {
        public string MembershipNumber { get; set; }
        public string AccountType { get; set; }
        public double Amount { get; set; }
    
        public virtual member member { get; set; }
    }
}
