//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentsheader
    {
        public string DocumentNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string Currency { get; set; }
        public string Payee { get; set; }
        public short Posted { get; set; }
        public string DateTimePosted { get; set; }
        public string PostedBy { get; set; }
        public double TotalPaymentAmount { get; set; }
        public string PayingBankAccount { get; set; }
        public string Status { get; set; }
        public string PaymentType { get; set; }
        public string DimCode1 { get; set; }
        public string DimCode2 { get; set; }
        public string BankName { get; set; }
        public double TotalVATAmount { get; set; }
        public double TotalWHTAmount { get; set; }
        public double TotalNetAmount { get; set; }
        public string ChequeNumber { get; set; }
        public string PayMode { get; set; }
        public string ChequeType { get; set; }
    }
}
