//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public short CanLogin { get; set; }
        public short IsMasterAdmin { get; set; }
        public short CanAddUser { get; set; }
        public short CanAddKin { get; set; }
        public short CanViewMemberProfile { get; set; }
        public short CanEditUser { get; set; }
        public short CanDeleteUser { get; set; }
        public short CanAddSavings { get; set; }
        public short CanAddWithdrawal { get; set; }
        public short CanAddBulkSavings { get; set; }
        public short CanAddLoan { get; set; }
        public short CanAddLoanRepayment { get; set; }
        public short CanViewRepaymentHistory { get; set; }
        public short CanViewLoanGuarantors { get; set; }
        public short CanEditLoan { get; set; }
        public short CanDeleteLoan { get; set; }
        public short CanAddShares { get; set; }
        public short CanViewShares { get; set; }
        public short CanAddExpenses { get; set; }
        public short CanEditExpenses { get; set; }
        public short CanDeleteExpenses { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
