//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaccoBookEntities : DbContext
    {
        public SaccoBookEntities()
            : base("name=SaccoBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<appprovaldocumentsetting> appprovaldocumentsettings { get; set; }
        public virtual DbSet<approvalentry> approvalentries { get; set; }
        public virtual DbSet<approvaluser> approvalusers { get; set; }
        public virtual DbSet<attachment> attachments { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<generalledgeraccount> generalledgeraccounts { get; set; }
        public virtual DbSet<guarantor> guarantors { get; set; }
        public virtual DbSet<loanprocucttype> loanprocucttypes { get; set; }
        public virtual DbSet<memberbankaccount> memberbankaccounts { get; set; }
        public virtual DbSet<memberbeneficiary> memberbeneficiaries { get; set; }
        public virtual DbSet<memberkin> memberkins { get; set; }
        public virtual DbSet<memberloanrepayment> memberloanrepayments { get; set; }
        public virtual DbSet<memberloan> memberloans { get; set; }
        public virtual DbSet<membermonthlycontribution> membermonthlycontributions { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<membersaving> membersavings { get; set; }
        public virtual DbSet<membersavingsaccount> membersavingsaccounts { get; set; }
        public virtual DbSet<membersharecapital> membersharecapitals { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<notificationtemplate> notificationtemplates { get; set; }
        public virtual DbSet<notificationtemplatesetting> notificationtemplatesettings { get; set; }
        public virtual DbSet<numbersery> numberseries { get; set; }
        public virtual DbSet<paymentsheader> paymentsheaders { get; set; }
        public virtual DbSet<resource> resources { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<savingsaccounttype> savingsaccounttypes { get; set; }
        public virtual DbSet<Signatory> Signatories { get; set; }
        public virtual DbSet<systemuser> systemusers { get; set; }
        public virtual DbSet<sytemsetting> sytemsettings { get; set; }
    }
}
