//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class savingsaccounttype
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double MinimumOpeningBalance { get; set; }
        public double MinimumMonthlyContributions { get; set; }
        public double MaximumAmountWithdrawableInADay { get; set; }
        public double WithdrawalCharge { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
