//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaccoBook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sytemsetting
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string HomePage { get; set; }
        public byte[] Photo { get; set; }
        public string AfricasTalkingUsername { get; set; }
        public string AfricasTalkingAPIKey { get; set; }
        public short SMSNotificationsEnabled { get; set; }
        public string SMTPServer { get; set; }
        public int SMTPServerPort { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public short EmailNotificationsEnabled { get; set; }
        public short AutomaticDatabaseBackUpEnabled { get; set; }
        public string DatabaseBackUpPath { get; set; }
        public string CredentialType { get; set; }
        public string LastModifiedBy { get; set; }
        public string LastModifiedAt { get; set; }
    }
}
