using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;

namespace SaccoBook.Modules.GeneralLedger
{
    public partial class GLAccount : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public GLAccount()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void _IsParentGLAccount_CheckedChanged(object sender, EventArgs e)
        {
            if(_IsParentGLAccount.Checked == true)
            {
                _ParentGLAccount.ReadOnly = true;
                _GLCode.Text = "";
            }
            else
            {
                _ParentGLAccount.ReadOnly = false;
            }
        }
        private void btn_save_ItemClick(object sender, ItemClickEventArgs e)
        {

            //Interest on loan: G/L Account
                       
            if (dxValidationProviderGLAccount.Validate().Equals(true))
            {
                // object displayMemeber = _ParentGLAccount.Properties.GetDisplayValueByKeyValue(_ParentGLAccount.EditValue);
                // MessageBox.Show(_ParentGLAccount.EditValue.ToString());

                if (EF.GeneralLedgerQueries.CreateGLAccount(_GLCode.Text, _ParentGLAccount.EditValue.ToString(), _Name.Text, _Description.Text, _AccountType.Text,  _BalanceSheetIncomeStatement.Text, _DirectPosting.Checked, 0, 0, 0, 0, _IsBlocked.Checked, Login.LoggedInUser, DateTime.Now.ToString()))
                {
                    XtraMessageBox.Show("Information has been successfully saved", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }

        private void _ParentGLAccount_EditValueChanged(object sender, EventArgs e)
        {
            _GLCode.Text = _ParentGLAccount.EditValue.ToString();
        }
    }
}