using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;

namespace SaccoBook.Modules.Settings.Notifications
{
    public partial class ViewNotificationTemplates : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        string DocumentNumber = null;
        public ViewNotificationTemplates()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
           // sqlDataSource1.Fill();
        }

        private void btn_newtemplate_ItemClick(object sender, ItemClickEventArgs e)
        {
            NotificationTemplate _NotificationTemplate = new NotificationTemplate();
            _NotificationTemplate.ShowDialog();
        }

        private void btn_edit_ItemClick(object sender, ItemClickEventArgs e)
        {
            if(DocumentNumber!= null)
            {
                NotificationTemplate _NotificationTemplate = new NotificationTemplate(DocumentNumber);
                _NotificationTemplate.ShowDialog();
            }
        }
    }
}