using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;

namespace SaccoBook.Modules.SavingsWithdrawals.Savings
{
    public partial class SavingsStatement : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        static string _AccountNumber = null;
        public SavingsStatement()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        public SavingsStatement(string AccountNumber)
        {
            InitializeComponent();
            _AccountNumber = AccountNumber;
            LoadAccountStatement(AccountNumber);
        }

        private void LoadAccountStatement(string accountNumber)
        {
            string sqlSavingsStatement = EF.SavingsQueries.SavingsStatementList(accountNumber);

            AppResources.AppFunctions.LoadTable(GridControlStatement, GridViewStatement, sqlSavingsStatement);
        }

        private void btn_refresh_ItemClick(object sender, ItemClickEventArgs e)
        {
            LoadAccountStatement(_AccountNumber);
        }
    }
}